// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// EScore
NumericVector EScore(NumericVector f);
RcppExport SEXP _selectSNPs_EScore(SEXP fSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type f(fSEXP);
    rcpp_result_gen = Rcpp::wrap(EScore(f));
    return rcpp_result_gen;
END_RCPP
}
// UScore
double UScore(NumericVector x);
RcppExport SEXP _selectSNPs_UScore(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(UScore(x));
    return rcpp_result_gen;
END_RCPP
}
// localScore
double localScore(NumericVector f, NumericVector x, double w1, double w2, double t1, double t2);
RcppExport SEXP _selectSNPs_localScore(SEXP fSEXP, SEXP xSEXP, SEXP w1SEXP, SEXP w2SEXP, SEXP t1SEXP, SEXP t2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type f(fSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type w1(w1SEXP);
    Rcpp::traits::input_parameter< double >::type w2(w2SEXP);
    Rcpp::traits::input_parameter< double >::type t1(t1SEXP);
    Rcpp::traits::input_parameter< double >::type t2(t2SEXP);
    rcpp_result_gen = Rcpp::wrap(localScore(f, x, w1, w2, t1, t2));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_selectSNPs_EScore", (DL_FUNC) &_selectSNPs_EScore, 1},
    {"_selectSNPs_UScore", (DL_FUNC) &_selectSNPs_UScore, 1},
    {"_selectSNPs_localScore", (DL_FUNC) &_selectSNPs_localScore, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_selectSNPs(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
