# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

EScore <- function(f) {
    .Call('_selectSNPs_EScore', PACKAGE = 'selectSNPs', f)
}

UScore <- function(x) {
    .Call('_selectSNPs_UScore', PACKAGE = 'selectSNPs', x)
}

localScore <- function(f, x, w1 = 0.5, w2 = 0.5, t1 = 1, t2 = 1) {
    .Call('_selectSNPs_localScore', PACKAGE = 'selectSNPs', f, x, w1, w2, t1, t2)
}

